---
- hosts: all
  roles:
    - role: xanmanning.k3s

- hosts: masters
  gather_facts: false
  tasks:
    - name: Replace 127.0.0.1 with control plane vip
      ansible.builtin.replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: "server: https://[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+:6443"
        replace: "server: https://{{ kube_vip.vip.ip_address }}:6443"
      become: true

    - name: Fetch .kube/config
      ansible.builtin.fetch:
        src:  /etc/rancher/k3s/k3s.yaml
        dest: credentials/kube/config
        flat: yes
      become: true
      run_once: true

- hosts: all
  tasks:
    - name: Blacklist rtl kernel modules
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        line: 'blacklist dvb_usb_rtl28xxu'
        regexp: '^blacklist dvb_usb_rtl28xxu'
        create: true
      become: true
      notify: reboot
  handlers:
    - name: reboot
      reboot:
      become: true

- hosts: all
  tasks:
    - name: Install rtl-sdr
      package:
        name:
          - rtl-sdr
          - rtl-433
      become: true

    - name: Install rtl-sdr udev rules
      template:
        src: rtl-sdr.rules
        dest: /etc/udev/rules.d/rtl-sdr.rules
      notify: reload-udev-rules
      become: true

  handlers:
    - name: reload-udev-rules
      shell: udevadm control --reload-rules && udevadm trigger
      become: true

- import_playbook: helm.yml
