---
cert_manager_state: present

cert_manager_helm_chart:
  chart_name: jetstack/cert-manager
  version: 1.8.2
  repositories:
    - name: jetstack
      repo_url: https://charts.jetstack.io
  name: cert-manager
  state: "{{ cert_manager_state }}"
  namespace: cert-manager
  values:
    installCRDs: true
  post_resources:
    - "{{ issuer_lets_encrypt_staging }}"
    - "{{ issuer_lets_encrypt_prod }}"
