---
prometheus_state: present

prometheus_retention: 4h

prometheus_extra_scrape_configs:
  "{{ speedtest_exporter_scrape_config +
      fronius_exporter_scrape_config +
      rtl_433_exporter_scrape_config +
      rtl_433_exporter_917_scrape_config
  }}"

prometheus_load_balancer_ip: 192.168.0.66

thanos_s3_access_key: "{{ lookup('env', 'THANOS_S3_ACCESS_KEY', default=undef()) }}"
thanos_s3_secret_key: "{{ lookup('env', 'THANOS_S3_SECRET_KEY', default=undef()) }}" 

thanos_s3_config:
  type: s3
  config:
    bucket: homelab-thanos-data #S3 bucket name
    endpoint: s3.ap-southeast-2.amazonaws.com #S3 Regional endpoint
    access_key: "{{ thanos_s3_access_key }}"
    secret_key: "{{ thanos_s3_secret_key }}"

prometheus_helm_chart:
  chart_name: prometheus-community/prometheus
  version: 15.5.0
  repositories:
    - name: prometheus-community
      repo_url: https://prometheus-community.github.io/helm-charts
    - name: kube-state-metrics
      repo_url: https://kubernetes.github.io/kube-state-metrics
  secrets:
    - name: thanos-storage-secret
      content:
        s3.yml: "{{ thanos_s3_config | to_nice_yaml | b64encode }}"
  name: prometheus
  state: "{{ prometheus_state }}"
  namespace: monitoring
  values:
    # My additions
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: false
    serverFiles:
      prometheus.yml:
        scrape_configs: "{{ prometheus_extra_scrape_configs | from_yaml }}"
    server:
      remoteWrite: "{{ prometheus_remote_write | default([]) }}"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist

      # From https://github.com/thanos-io/thanos/tree/main/tutorials/kubernetes-helm
      # with some modifications
      extraArgs:
        # log.level: debug
        storage.tsdb.min-block-duration: 2h  # Don't change this, see docs/components/sidecar.md
        storage.tsdb.max-block-duration: 2h  # Don't change this, see docs/components/sidecar.md
      retention: 4h
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9090"
        gRPC:
          enabled: true
      statefulSet:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
      sidecarContainers:
      - name: thanos-sidecar
        # Always use explicit image tags (release or main-<date>-sha) instead of ambigous `latest` or `main`.
        # Check https://quay.io/repository/thanos/thanos?tab=tags to get latest tag.
        image: quay.io/thanos/thanos:main-2022-06-27-37cc176c
        args:
        - "sidecar"
        - "--log.level=debug"
        - "--tsdb.path=/data/"
        - "--prometheus.url=http://127.0.0.1:9090"
        - "--objstore.config-file=/etc/secret/s3.yml"
        - "--reloader.config-file=/etc/prometheus-config/prometheus.yml"
        - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
        - "--reloader.rule-dir=/etc/prometheus-config/rules"
        ports:
        - name: sidecar-http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: storage-volume
          mountPath: /data
        - name: thanos-storage-secret
          mountPath: /etc/secret
        - name: config-volume
          mountPath: /etc/prometheus-config
          readOnly: false
        - name: prometheus-config-shared
          mountPath: /etc/prometheus-shared/
          readOnly: false
      configPath: /etc/prometheus-shared/prometheus.yml
      replicaCount: 1
      persistentVolume:
        size: 2Gi
      extraVolumes:
      - name: prometheus-config-shared
        emptyDir: {}
      extraVolumeMounts:
      - name: prometheus-config-shared
        mountPath: /etc/prometheus-shared/
      global:
        # scrape_interval: 5s
        # scrape_timeout: 4s
        external_labels:
          prometheus_group: HOMELAB
          prometheus_replica: '$(HOSTNAME)'
        # evaluation_interval: 5s
      extraSecretMounts:
      - name: thanos-storage-secret
        mountPath: /etc/secret/
        readOnly: false
        secretName: thanos-storage-secret
    configmapReload:
      image:
        repository: gcr.io/google-containers/pause-arm64 # This image changed to just pause since there's no option to disable configmapReload container in chart, but thanos-sidecar overtakes this functionality. So basically we don't need another reloader
        tag: 3.2
