---
route53_dynamic_dns_state: present

route53_dynamic_dns_aws_access_key_id: "{{ lookup('env', 'ROUTE53_DYNAMIC_DNS_AWS_ACCESS_KEY_ID', default=undef()) }}"
route53_dynamic_dns_aws_access_key: "{{ lookup('env', 'ROUTE53_DYNAMIC_DNS_AWS_ACCESS_KEY', default=undef()) }}"

route53_dynamic_dns_helm_chart:
  chart_name: markafarrell/route53-dynamic-dns
  version: 1.0.0
  repositories:
    - name: markafarrell
      repo_url: https://markafarrell.github.io/helm-charts/
  name: route53-dynamic-dns
  state: "{{ route53_dynamic_dns_state }}"
  namespace: route53-dynamic-dns
  secrets:
    - name: route53-dynamic-dns-aws-secret
      content:
        AWS_ACCESS_KEY_ID: "{{ route53_dynamic_dns_aws_access_key_id | b64encode }}"
        AWS_ACCESS_KEY: "{{ route53_dynamic_dns_aws_access_key | b64encode }}"
  values:
    env:
      ROUTE53_DOMAIN: '*.homelab.evilcyborgdrone.com'
      ROUTE53_HOSTED_ZONE_ID: "{{ lookup('env', 'ROUTE53_HOSTED_ZONE_ID', default=undef()) }}"
      