---
rtl_433_exporter_state: present
rtl_433_exporter_namespace: temperature-monitoring
rtl_433_exporter_interval: 1m

rtl_433_exporter_scrape_config: |
  - job_name: 'rtl-433-exporter'
    scrape_interval: "{{ rtl_433_exporter_interval }}"
    scrape_timeout: 1m
    static_configs:
      - targets: ['rtl-433-exporter.{{ rtl_433_exporter_namespace }}.svc.cluster.local:9550']

rtl_433_exporter_helm_chart:
  chart_name: markafarrell/rtl-433-exporter
  repositories:
    - name: markafarrell
      repo_url: https://markafarrell.github.io/helm-charts/
  name: rtl-433-exporter
  state: "{{ rtl_433_exporter_state }}"
  namespace: "{{ rtl_433_exporter_namespace }}"
  values: # {}
    image:
      tag: 1.2.3
    env:
      MATCHERS: >
        --id_matcher=Nexus-TH,110,Lucas-Room
        --id_matcher=Nexus-TH,222,Front-Room
        --id_matcher=Nexus-TH,238,Master-Bedroom
        --id_matcher=Nexus-TH,36,Kitchen
        --id_matcher=Nexus-TH,75,Evans-Room
    nodeSelector:
      kubernetes.io/hostname: kube-worker-1