---
thanos_state: present

thanos_s3_access_key: "{{ lookup('env', 'THANOS_S3_ACCESS_KEY', default=undef()) }}"
thanos_s3_secret_key: "{{ lookup('env', 'THANOS_S3_SECRET_KEY', default=undef()) }}" 

thanos_s3_config:
  type: s3
  config:
    bucket: homelab-thanos-data #S3 bucket name
    endpoint: s3.ap-southeast-2.amazonaws.com #S3 Regional endpoint
    access_key: "{{ thanos_s3_access_key }}"
    secret_key: "{{ thanos_s3_secret_key }}"

thanos_helm_chart:
  chart_name: markafarrell/thanos
  version: 1.0.1
  repositories:
    - name: markafarrell
      repo_url: https://markafarrell.github.io/helm-charts/
  name: thanos
  state: "{{ thanos_state }}"
  namespace: monitoring
  secrets:
    - name: thanos-storage-secret
      content:
        s3.yml: "{{ thanos_s3_config | to_nice_yaml | b64encode }}"
  values:
    store:
      objStoreConfigFile: /etc/secret/s3.yml
      extraArgs:
        sync-block-duration: 1h
